export const escudos: Record<string, string> = {
  "Albion FC": "/escudos/albion-fc.png",
  "Boston River": "/escudos/boston-river.png",
  "CA Cerro": "/escudos/ca-cerro.png",
  "CA Juventud": "/escudos/ca-juventud.png",
  "CA Progreso": "/escudos/ca-progreso.png",
  "CD Maldonado": "/escudos/cd-maldonado.png",
  "Central Español FC": "/escudos/central-espanol-fc.png",
  "Cerro Largo": "/escudos/cerro-largo.png",
  "Danubio FC": "/escudos/danubio-fc.png",
  "Defensor SC": "/escudos/defensor-sc.png",
  "Liverpool FC Montevideo": "/escudos/liverpool-fc-montevideo.png",
  "Montevideo City Torque": "/escudos/montevideo-city-torque.png",
  "Montevideo Wanderers": "/escudos/montevideo-wanderers.png",
  Nacional: "/escudos/nacional.png",
  Peñarol: "/escudos/penarol.png",
  "Racing Club de Montevideo": "/escudos/racing-club-de-montevideo.png",
};
