/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TacaRouteImport } from './routes/taca'
import { Route as TeamValuesRouteImport } from './routes/team-values'
import { Route as ClubeSlugRouteImport } from './routes/clube.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TacaRoute = TacaRouteImport.update({
  id: '/taca',
  path: '/taca',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamValuesRoute = TeamValuesRouteImport.update({
  id: '/team-values',
  path: '/team-values',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeSlugRoute = ClubeSlugRouteImport.update({
  id: '/clube/$slug',
  path: '/clube/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/classificacao': typeof ClassificacaoRoute
  '/login': typeof LoginRoute
  '/taca': typeof TacaRoute
  '/team-values': typeof TeamValuesRoute
  '/clube/$slug': typeof ClubeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/classificacao': typeof ClassificacaoRoute
  '/login': typeof LoginRoute
  '/taca': typeof TacaRoute
  '/team-values': typeof TeamValuesRoute
  '/clube/$slug': typeof ClubeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/classificacao': typeof ClassificacaoRoute
  '/login': typeof LoginRoute
  '/taca': typeof TacaRoute
  '/team-values': typeof TeamValuesRoute
  '/clube/$slug': typeof ClubeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/classificacao'
    | '/login'
    | '/taca'
    | '/team-values'
    | '/clube/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/classificacao'
    | '/login'
    | '/taca'
    | '/team-values'
    | '/clube/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/classificacao'
    | '/login'
    | '/taca'
    | '/team-values'
    | '/clube/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  LoginRoute: typeof LoginRoute
  TacaRoute: typeof TacaRoute
  TeamValuesRoute: typeof TeamValuesRoute
  ClubeSlugRoute: typeof ClubeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taca': {
      id: '/taca'
      path: '/taca'
      fullPath: '/taca'
      preLoaderRoute: typeof TacaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-values': {
      id: '/team-values'
      path: '/team-values'
      fullPath: '/team-values'
      preLoaderRoute: typeof TeamValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/$slug': {
      id: '/clube/$slug'
      path: '/clube/$slug'
      fullPath: '/clube/$slug'
      preLoaderRoute: typeof ClubeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  LoginRoute: LoginRoute,
  TacaRoute: TacaRoute,
  TeamValuesRoute: TeamValuesRoute,
  ClubeSlugRoute: ClubeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
